version: '3'

services:
  backend:
    ports:
    - 5005:5005

  mongodb:
    ports:
      - 27017:27017

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=pass123
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #   depends_on:
  #     - mongodb
  #   restart: unless-stopped

  minio:
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
