version: '3'

volumes:
  mongo-data:
    driver: local

services:
  api:
    build: ./backend
    image: armk-be:v1
    container_name: armk-be
    command: npm run start
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://admin:pass123@mongodb:27017
    depends_on:
      - mongodb


  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass123
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass123
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
